### PR TITLE
Update to 18.1

### PR DESCRIPTION
**Pull request by brianmcmichael**
Update to v 18.1

See INC0322897

### CODE REVIEW

**Comment by nickjer** [comment]
Please open a task up in Asana for this so we can better track this through the software deployment lifecycle.

**Comment by nickjer** [comment]
You will definitely need to walk through:

- a CFX example with MPI to confirm that the custom `template/cfx_assets/start-methods.ccl` still work (make sure the hosts are properly being populated in the GUI)
- a Fluent example with MPI to confirm `Fluent Parallel Info` from the `template/fluxbox/menu` still gives accurate information

You will also need to test that CFX pre/post visualization works with and without `vis` node type selected due to the `CUE_GRAPHICS` env var being properly set.

Bonus points, you can confirm that the CFX/Fluent MPI runs start up processes under `pbs_mom` on the compute nodes.

**Comment by brianmcmichael** [comment]
https://app.asana.com/0/425364008343147/475427362403540

**Comment by nickjer** [comment]
That task is for migrating the apps to Owens and not updating the app on Oakley. Also you should make individual tasks for each app as their deployment lifecycles are separate.

So for each app you will have an Asana task with the following subtasks:

- [ ] update code
- [ ] review code
- [ ] deploy to webdev02/04
- [ ] test it on webdev02/04
- [ ] release/tag code
- [ ] deploy to webtest02/04
- [ ] test it on webtest02/04
- [ ] deploy to web02/04

This helps the release engineer to know what needs to go out and he/she can check off each app that was deployed.

**Comment by brianmcmichael** [comment]
Closing as duplicate of https://github.com/OSC/bc_osc_ansys_workbench/pull/4

**Pull request closed without merging**
