### PR TITLE
Update to 18.1

### LINKED ISSUE #3: Upgrade to use new Dashboard ERB templating

### LINKED ISSUE #6: Add support for ANSYS 18.1
We currently support ANSYS 15.0.7. We should also add support for 18.1 on Oakley.

### PR DESCRIPTION
**Pull request by brianmcmichael**
Fixes #3 
Fixes #6 

[INC0324540](https://oarnet.service-now.com/nav_to.do?uri=incident.do?sys_id=5b8a65e3db9fcf00ec2d2feb0b9619ac)

Ansys Workbench is not installed on Owens. For now this is updated to launch v18.1 on Oakley. 

Scientific Applications will need to install Ansys Workbench before this can be ported to Owens.

### CODE REVIEW

**Comment by nickjer** [comment]
A *couple* of things (if these are done already then feel free to check it off):

- [ ] confirm whether this is for Ansys 18.1 or 17.2 (since Asana task says 17.2)
- [ ] add this PR link to the S/N ticket so that it is tracked (as a work note)
- [ ] add the S/N ticket link here (preferably in your first post for this PR) so that we can reference it
- [ ] add this PR link to the Asana task description
- [ ] add the link for this PR to the corresponding change in the CHANGELOG (see what we do for [Dashboard CHANGELOG](https://raw.githubusercontent.com/OSC/ood-dashboard/master/CHANGELOG.md), you do not need to update the CHANGELOG to the new formatting, instead an issue should be created for that)
- [ ] update Asana task to appropriate Kanban column
- [ ] run a multi-node Fluent example case (confirm with `top` on each node that it uses all the cores on all the nodes when solving)
- [ ] run a multi-node CFX example case (confirm with `top` on each node that it uses all the cores on all the nodes when solving)
- [ ] run using both the `any` and `vis` node types and confirm nothing breaks
- [ ] if no changes were made to the underlying template code, then you do not need to update the README to say it supports Ansys 18.1+ as 15.0.7+ would still be true
- [ ] assign Asana task to me when code is ready for review

**Review by nickjer — CHANGES_REQUESTED** [review]
See my checklist below...

**Comment by nickjer** [comment]
A *couple* of things (if these are done already then feel free to check it off):

- [x] confirm whether this is for Ansys 18.1 or 17.2 (since Asana task says 17.2)
- [x] add this PR link to the S/N ticket so that it is tracked (as a work note)
- [x] add the S/N ticket link here (preferably in your first post for this PR) so that we can reference it
- [x] add this PR link to the Asana task description
- [x] add the link for this PR to the corresponding change in the CHANGELOG (see what we do for [Dashboard CHANGELOG](https://raw.githubusercontent.com/OSC/ood-dashboard/master/CHANGELOG.md), you do not need to update the CHANGELOG to the new formatting, instead an issue should be created for that)
- [x] update Asana task to appropriate Kanban column
- [ ] run a multi-node Fluent example case (confirm with `top` on each node that it uses all the cores on all the nodes when solving)
- [ ] run a multi-node CFX example case (confirm with `top` on each node that it uses all the cores on all the nodes when solving)
- [ ] run using both the `any` and `vis` node types and confirm nothing breaks
- [x] if no changes were made to the underlying template code, then you do not need to update the README to say it supports Ansys 18.1+ as 15.0.7+ would still be true
- [ ] move Asana task to Review and assign Asana task to me when code is ready for review

**Comment by brianmcmichael** [comment]
Since several of these versions are available on Oakley and the code modifications are very minimal, it may make more sense to do this as an <option> and allow the user to select the version. So if the user wants 17.2 instead of 18.1 they can use it. I'm not sure what the benefit of using the older version in this case would be, however. The batch connect configuration process is not documented right now and so I will need to figure out how to configure the form by looking at other applications that use that feature.

**Comment by nickjer** [comment]
I am able to get one example to run in ANSYS 18.1 + CFX, but the rest fail with strange errors. I think it might be due to version incompatibility with the example files (15.0.7), but I am not provided examples for 18.1.

**Pull request merged**
